### PR TITLE
Fix css

### LINKED ISSUE #2: Fix the CSS
The CSS is a mess because of stuff...

Needs sorting out so it is themeable and consistent.
Needs accessibility sorting out 
Layout needs work

### PR DESCRIPTION
**Pull request by chrissainty**
Resolves #2 
Styling updates

### CODE REVIEW

**Comment by SQL-MisterMagoo** [comment]
Can you take a look at the branch fix-css-webcompiler to see if you would be happy using that instead of gulp and node_modules?

**Comment by chrissainty** [comment]
Gulp and NPM are now removed and I've updated to webcompiler. Good shout on that.

There is still work to do with styling and making things responsive. But I would rather leave the rest of this work until things have settled with breaking down components and separating things out. 

The final style work can be done at the end before we do the first release. Would you be happy with that?

**Comment by SQL-MisterMagoo** [comment]
I'm very happy - let's merge this !

**Comment by chrissainty** [comment]
Done!

**Pull request merged**
