### PR TITLE
Replace gulp+npm with MSBuild+Excubo.WebCompiler

### PR DESCRIPTION
**Pull request by chucker**
See #81 

This needs to be tested a bit more:

- [x] Do the final CSS and JS behave correctly?
- [x] Does Excubo.WebCompiler get installed automatically? Do we need a `dotnet tool restore` task?

### CODE REVIEW

**Comment by chucker** [comment]
So, it seems fine to me.

@SQL-MisterMagoo, can you expand on what you meant with this:

> it has issues with @import when it is combining files (it doesn't move them to the top of the file)

I can't see any problem with the final stylesheet, other than `loader.css` missing, but I believe that was the case before (it's probably obsolete?).

**Comment by SQL-MisterMagoo** [comment]
> I can't see any problem with the final stylesheet, other than `loader.css` missing, but I believe that was the case before (it's probably obsolete?).

At some point we had a problem with @import lines not being handled correctly, but that doesn't seem to be happening any more, so all good.

**Comment by chucker** [comment]
I think this is good to go, then.

**Comment by SQL-MisterMagoo** [comment]
Thanks @chucker

**Pull request merged**
