### PR TITLE
2019-09-17 DNC 3.0.0 RC1 & Settings update

### PR DESCRIPTION
**Pull request by MarkStega**
@sql-mistermagoo @chrissainty
This PR has a much cleaner implementation of the settings dialog as well as support for DNC 3.0.0 RC1

There is a sample project called Blazor.Gitter.Settings which is a server side demo of the settings dialog. This entire project can be deleted once the settings dialog is fully integrated. I left it in place only to show how setting work without the css difficulties.

Missing (and I need help):
1) The settings page is being rendered but with really odd placement of the h1 title and the invoke button.
2) The settings page when invoked needs css styling.
3) The resultant settings are not used in Blazored.Gitter.

### CODE REVIEW

**Comment by SQL-MisterMagoo** [comment]
Thanks Mark - I'll pull this down and have a look

**Comment by MarkStega** [comment]
@SQL-MisterMagoo I solved the issue of why the settings dialog was not getting rendered. Now I think it just needs major css help on the settings page & the dialog as well as then actually using the settings.

**Comment by SQL-MisterMagoo** [comment]
We never got around to implementing this - and it is very far behind now - maybe we can cherry pick some commits from it if we get back to adding settings.

Thanks for the PR.

**Comment by chucker** [comment]
Is there a screenshot or sketch of what this settings dialog did?

**Comment by SQL-MisterMagoo** [comment]
I can probably force it to run and get one

**Pull request closed without merging**
