### PR TITLE
Move chat.js to use TypeScript

### PR DESCRIPTION
**Pull request by chucker**

### CODE REVIEW

**Review by SQL-MisterMagoo — CHANGES_REQUESTED** [review]
I am getting build errors when I checkout this branch to test.
They seem to appear when the Microsoft.TypeScript.MSBuild package is added.
Could  you take a look and see what might be going wrong?

**Comment by chucker** [comment]
Sure, sorry about that. I’ll have a look!

**Comment by SQL-MisterMagoo** [comment]
It could be something I'm missing locally but it complains about
IDisposable not found etc.
Very odd

**Comment by chucker** [comment]
I tried on a second system and it seemed to have trouble finding `gulp` (which in turn causes the `Core` project to fail to build). Maybe that's what you ran into. Try again with the minor change I just pushed.

**Comment by SQL-MisterMagoo** [comment]
I was still seeing errors with this, but I deleted node_modules (ugh I hate that folder) and removed Microsoft.TypeScript.MSBuild and it built, then I reset the branch back to your last commit and rebuilt and it built - my guess is something in my node_modules folder was wrong. Anyway I think we'll plough on as we are now.

**Review by SQL-MisterMagoo — APPROVED** [review]

**Comment by chucker** [comment]
> ugh I hate that folder

Aye. Gulp was already there so I built on top of it, but ideally, we’d avoid the npm ecosystem here.

That’s for another PR. Someday.

**Pull request merged**
